### ISSUE TITLE
1080p support

### ISSUE THREAD

**Issue by jbaconbits** [plexinc-plugins/IGN.bundle#9]
It looks like IGN is now doing videos in 1080p, but the channel still only has 720p has the highest available setting. The Transistor review is an example of one in 1080p.
http://www.ign.com/articles/2014/05/20/transistor-review

Possible to add 1080p support?

Thanks.

**Comment by sander1** [comment]
Added in https://github.com/plexinc-plugins/Services.bundle/commit/51e05976638af2d6cbd1527d29839c92ef4b226d
